<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quotation.Management.Contracts\Quotation.Management.Contracts.csproj" />
    <ProjectReference Include="..\Quotation.Management.Entities\Quotation.Management.Entities.csproj" />
  </ItemGroup>

</Project>
